nginx:
  image: nginx
  ports:
    - "80:80"
messagequeue:
  image: rabbitmq:3-management
  ports:
    - "5672:5672"
    - "15672:15672"
plm:
  image: webplm
  volumes:
    - "~/.plm:/root/.plm"
    - "~/webPLM/logs/:/app/webplm-dist/logs"
  ports:
    - "443:9443"
  environment:
    GITHUB_CLIENT_SECRET:
    GOOGLE_CLIENT_SECRET:
    PLMACCOUNTS_CLIENT_SECRET:
    GITHUB_ACCESS_TOKEN:
  links:
    - accounts
    - profiles
    - messagequeue:messageq
accounts:
  image: plm-accounts
  ports:
    - "9000:3000"
  links:
    - db
profiles:
  image: plm-profiles
  ports:
    - "8080:3000"
  links:
    - db
db:
  image: mongo
  volumes:
    - "~/mongodb/data:/data/db"
  ports: 
    - "27017:27017"
